DATA = 'data/'
GENERATED_DATASETS = 'data/generated_datasets/'
GENERATED_DATASETS_INNER = 'data/generated_datasets/inner/'
IMAGES = 'data/annotated_images/'
#LABELME_JSONS = 'data/labelme_jsons/'
POINT_LABELS = 'data/point_labels/'
WIDTH_MEASUREMENTS = 'data/width_measurements'